//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finances.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro no servidor ao criar a sua conta..
        /// </summary>
        public static string ErrorCreatingAccount {
            get {
                return ResourceManager.GetString("ErrorCreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro inesperado ao tentar deslogar..
        /// </summary>
        public static string ErrorLoggingOut {
            get {
                return ResourceManager.GetString("ErrorLoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao salvar o token de autenticação..
        /// </summary>
        public static string ErrorSaveAuthToken {
            get {
                return ResourceManager.GetString("ErrorSaveAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um problema ao consultar os usuários existentes..
        /// </summary>
        public static string ErrorSearchingForUsers {
            get {
                return ResourceManager.GetString("ErrorSearchingForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com esse nome de usuário..
        /// </summary>
        public static string ErrorUserAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado ainda não está logado..
        /// </summary>
        public static string ErrorUserNotLoggedYet {
            get {
                return ResourceManager.GetString("ErrorUserNotLoggedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login e/ou senha incorretos..
        /// </summary>
        public static string LoginAndOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("LoginAndOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login autorizado..
        /// </summary>
        public static string LoginAuthorized {
            get {
                return ResourceManager.GetString("LoginAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada está incorreta..
        /// </summary>
        public static string PasswordInformedIsIncorrect {
            get {
                return ResourceManager.GetString("PasswordInformedIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta criada com sucesso..
        /// </summary>
        public static string SuccessAccountCreation {
            get {
                return ResourceManager.GetString("SuccessAccountCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário deslogado com sucesso..
        /// </summary>
        public static string SuccessUserLoggedOut {
            get {
                return ResourceManager.GetString("SuccessUserLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuário não possui permissão de acesso..
        /// </summary>
        public static string UserDoesntHaveAccessPermission {
            get {
                return ResourceManager.GetString("UserDoesntHaveAccessPermission", resourceCulture);
            }
        }
    }
}
